### ISSUE TITLE
pdf crawling, client secret 갱신 자동화

### ISSUE THREAD

**Issue by jpham005** [42Statistics/42Stat-Crawler#2]
방식은 https://github.com/42Statistics/42Stat-Backend/issues/309 참고

로그인은 가상 브라우저를 통해 진행하는 방식으로 구현했고,
동시에 client secret 업데이트 까지 한 번에 자동화 할 수 있다고 판단돼 같이 작업하기로 했습니다.

**Comment by niamu01** [comment]
pdf
- [x] db 연결
- [x] puppeteer 로 링크 가져오기
- [x] curl 로 파일 받기 
  - [x] fetch 로 변경해보기
- [x] s3 연결

client secret
- [x] puppeteer 로 새로운 시크릿 키 가져오기
- [x] main 에 바로 push 되는 형태로 제작
- [ ] lambda 와 코드가 거의 겹쳐 input 으로 나누는 과정
- [ ] 동시에 dev, prod 나눠서 실행하도록 설정

env
- [ ] 각 키 넣고 다시 커밋

+)
- [ ] 어느 곳에서 실행할지에 따라 db연결을 위해 터널링이 필요할 수 있음

**Comment by jpham005** [comment]
일단 다 동작하는 코드를 만들긴 했는데,
42 client secret 갱신하는 부분이 기존에는 단일 repo, branch, deploy 라서 흐름이 깔끔했지만,
현재는 4개의 secret 을 3가지 다른 방법으로 배포해야 하는 문제가 있습니다.
이를 해결하기 위해 aws secret manager 를 도입하는게 낫겠다고 판단이 되어,
관련 로직 개선을 시도해보려 합니다.
